/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountSettingsAccount: typeof import('./src/components/account-settings/AccountSettingsAccount.vue')['default']
    AccountSettingsNotification: typeof import('./src/components/account-settings/AccountSettingsNotification.vue')['default']
    AccountSettingsSecurity: typeof import('./src/components/account-settings/AccountSettingsSecurity.vue')['default']
    AnalyticsAward: typeof import('./src/components/dashboard/AnalyticsAward.vue')['default']
    AnalyticsBarCharts: typeof import('./src/components/dashboard/AnalyticsBarCharts.vue')['default']
    AnalyticsDepositWithdraw: typeof import('./src/components/dashboard/AnalyticsDepositWithdraw.vue')['default']
    AnalyticsSalesByCountries: typeof import('./src/components/dashboard/AnalyticsSalesByCountries.vue')['default']
    AnalyticsTotalEarning: typeof import('./src/components/dashboard/AnalyticsTotalEarning.vue')['default']
    AnalyticsTotalProfitLineCharts: typeof import('./src/components/dashboard/AnalyticsTotalProfitLineCharts.vue')['default']
    AnalyticsTransactions: typeof import('./src/components/dashboard/AnalyticsTransactions.vue')['default']
    AnalyticsUserTable: typeof import('./src/components/dashboard/AnalyticsUserTable.vue')['default']
    AnalyticsWeeklyOverview: typeof import('./src/components/dashboard/AnalyticsWeeklyOverview.vue')['default']
    ApexCharts: typeof import('./src/components/charts/apex-chart/ApexCharts.vue')['default']
    AuthProvider: typeof import('./src/components/authentication/AuthProvider.vue')['default']
    BarChart: typeof import('./src/components/charts/apex-chart/BarChart.vue')['default']
    CardBasic: typeof import('./src/components/card-basic/CardBasic.vue')['default']
    CardNavigation: typeof import('./src/components/card-basic/CardNavigation.vue')['default']
    CardSolid: typeof import('./src/components/card-basic/CardSolid.vue')['default']
    CardStatisticsHorizontal: typeof import('./src/@core/components/cards/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/cards/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/cards/CardStatisticsWithImages.vue')['default']
    DemoFormLayoutHorizontalForm: typeof import('./src/components/forms/form-layouts/DemoFormLayoutHorizontalForm.vue')['default']
    DemoFormLayoutHorizontalFormWithIcons: typeof import('./src/components/forms/form-layouts/DemoFormLayoutHorizontalFormWithIcons.vue')['default']
    DemoFormLayoutMultipleColumn: typeof import('./src/components/forms/form-layouts/DemoFormLayoutMultipleColumn.vue')['default']
    DemoFormLayoutVerticalForm: typeof import('./src/components/forms/form-layouts/DemoFormLayoutVerticalForm.vue')['default']
    DemoFormLayoutVerticalFormWithIcons: typeof import('./src/components/forms/form-layouts/DemoFormLayoutVerticalFormWithIcons.vue')['default']
    DemoSimpleTableBasics: typeof import('./src/components/tables/DemoSimpleTableBasics.vue')['default']
    DemoSimpleTableDensity: typeof import('./src/components/tables/DemoSimpleTableDensity.vue')['default']
    DemoSimpleTableFixedHeader: typeof import('./src/components/tables/DemoSimpleTableFixedHeader.vue')['default']
    DemoSimpleTableHeight: typeof import('./src/components/tables/DemoSimpleTableHeight.vue')['default']
    DemoSimpleTableTheme: typeof import('./src/components/tables/DemoSimpleTableTheme.vue')['default']
    ErrorHeader: typeof import('./src/components/ErrorHeader.vue')['default']
    Keyboard: typeof import('./src/components/charts/echarts/Keyboard.vue')['default']
    LineChart: typeof import('./src/components/charts/apex-chart/LineChart.vue')['default']
    LineMarker: typeof import('./src/components/charts/echarts/LineMarker.vue')['default']
    MixChart: typeof import('./src/components/charts/apex-chart/MixChart.vue')['default']
    MoreBtn: typeof import('./src/@core/components/MoreBtn.vue')['default']
    PieChart: typeof import('./src/components/charts/echarts/PieChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableBasic: typeof import('./src/components/tables/TableBasic.vue')['default']
    TableDark: typeof import('./src/components/tables/TableDark.vue')['default']
    TableDensity: typeof import('./src/components/tables/TableDensity.vue')['default']
    TableFixedHeader: typeof import('./src/components/tables/TableFixedHeader.vue')['default']
    TableHeight: typeof import('./src/components/tables/TableHeight.vue')['default']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    TypographyHeadlines: typeof import('./src/components/typography/TypographyHeadlines.vue')['default']
    TypographyTexts: typeof import('./src/components/typography/TypographyTexts.vue')['default']
    UpgradeToPro: typeof import('./src/components/UpgradeToPro.vue')['default']
    VueApexCharts: typeof import('vue3-apexcharts')['default']
  }
}
